ipq807x: hotplug: open MHI pipe-14  only
Current script is opening all the MHI pipes
up on hotplug event, and is causing other issues,
opeining pipe 14 will be suffice for data call.

Signed-off-by: Venkat Raju Sana <vrsana@codeaurora.org>
Change-Id: I0bfba7098060fccdb1fec67de3ba7f6d14183c6b
Signed-off-by: Venkat Raju Sana <vrsana@codeaurora.org>

diff --git a/target/linux/ipq/base-files/etc/hotplug.d/mhi_uci/00-mhiuci b/target/linux/ipq/base-files/etc/hotplug.d/mhi_uci/00-mhiuci
--- a/target/linux/ipq/base-files/etc/hotplug.d/mhi_uci/00-mhiuci
+++ b/target/linux/ipq/base-files/etc/hotplug.d/mhi_uci/00-mhiuci
@@ -15,18 +15,18 @@
  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 '
 
-if [ -e /dev/$DEVICENAME ] && [ "$ACTION" = add ]; then
-        cd /dev
-        cat /dev/$DEVICENAME &
-        foo_pid=$!
-        if [ $? -eq 0 ]; then
-                printf "Sending udev events over mhi-uci" \
-                                                                > /dev/console
-        else
-                printf "Failed in sending udev events over  mhi-uci, check pci link and qrtr etc " \
-                                                                > /dev/console
-        fi
-        cd -
+DEVICE="mhi_0306_00.01.00_pipe_14"
 
+if [ "$ACTION" = add ]; then
+	if [ "$DEVICENAME" == "$DEVICE" ]; then
+		cat /dev/$DEVICENAME &
+		if [ $? -eq 0 ]; then
+			printf "Sending udev events over mhi-uci" \
+								> /dev/console
+		else
+			printf "Failed in sending udev events over  mhi-uci, check pci link and qrtr etc " \
+								> /dev/console
+		fi
+	fi
 fi
 
