base-files/wifi: Add back provision to unload/load wifi modules
Enable provision for unloading and loading of wifi modules,
this is required when we want to test wifi with module
parameters configured via UCI, seems this change got wiped out
during latest FFW

Change-Id: Iaa8f1c3b35feef94240dcd184de8aa4a13f7b324
Signed-off-by: Mohammed Shafi Shajakhan <mohammed@codeaurora.org>

diff --git a/package/base-files/files/sbin/wifi b/package/base-files/files/sbin/wifi
--- a/package/base-files/files/sbin/wifi
+++ b/package/base-files/files/sbin/wifi
@@ -234,6 +234,23 @@ scan_wifi() {
 	config_load "${cfgfile:-wireless}"
 }
 
+wifi_load() {
+       for driver in ${1:-$DRIVERS}; do (
+               if eval "type unload_$driver" 2>/dev/null >/dev/null; then
+                       eval "unload_$driver" || echo "$driver: unload failed" >&2
+               else
+                       echo "$driver: wifi unload not supported" >&2
+               fi
+       ); done
+       for driver in ${1:-$DRIVERS}; do (
+               if eval "type load_$driver" 2>/dev/null >/dev/null; then
+                       eval "load_$driver" || echo "$driver: load failed" >&2
+               else
+                       echo "$driver: wifi load not supported" >&2
+               fi
+       ); done
+}
+
 DEVICES=
 DRIVERS=
 include /lib/wifi
@@ -245,6 +262,7 @@ case "$1" in
 	status) ubus_wifi_cmd "status" "$2";;
 	reload) wifi_reload "$2";;
 	reload_legacy) wifi_reload_legacy "$2";;
+	load) wifi_load "$2";;
 	--help|help) usage;;
 	*) ubus call network reload; wifi_updown "enable" "$2";;
 esac
