ipq: Modify script to do VAP level wifi down/up
Modify wifi script to take VAP interface name along
with radio interface name to apply/modify configurations
only for given VAP by unaltering other VAPs.

Commands:
i.Existing commands:
wifi                   : Do down/up for all VAPs of all radios
wifi down              : Do down for all VAPs of all radios
wifi up                : Do up for all VAPs of all radios

ii. Newly introduced:
wifi down wifiX        : Do down for all VAPs belongs to wifiX
wifi up wifiX          : Do up for all VAPs belongs to wifiX
wifi down wifiX athX   : Do down for athX belongs to wifiX
wifi up wifiX athX     : Do up for athX belongs to wifiX

Change-Id: Ida92c74fff2f22cf1426bbbcee9941c52d053bc8
Signed-off-by: Shreedhar Parande <sparande@codeaurora.org>
Signed-off-by: Sandhya KS <sandhyks@codeaurora.org>

diff --git a/package/base-files/files/sbin/wifi b/package/base-files/files/sbin/wifi
--- a/package/base-files/files/sbin/wifi
+++ b/package/base-files/files/sbin/wifi
@@ -123,7 +123,7 @@ _wifi_updown() {
 		config_get iftype "$device" type
 		if eval "type ${1}_$iftype" 2>/dev/null >/dev/null; then
 			eval "scan_$iftype '$device'"
-			eval "${1}_$iftype '$device'" || echo "$device($iftype): ${1} failed"
+			eval "${1}_$iftype '$device' '$3'" || echo "$device($iftype): ${1} failed"
 		elif [ ! -f /lib/netifd/wireless/$iftype.sh ]; then
 			echo "$device($iftype): Interface type not supported"
 		fi
@@ -139,7 +139,7 @@ _wifi_updown() {
 wifi_updown() {
 	cmd=down
 	[ enable = "$1" ] && {
-		_wifi_updown disable "$2"
+		_wifi_updown disable "$2" "$3"
 		ubus_wifi_cmd "$cmd" "$2"
 		scan_wifi
 		cmd=up
@@ -286,7 +286,7 @@ scan_wifi
 trap 'wifi_trap; exit' INT TERM ABRT QUIT ALRM
 
 case "$1" in
-	down) wifi_updown "disable" "$2";;
+	down) wifi_updown "disable" "$2" "$3";;
 	detect) wifi_detect_notice ;;
 	config) wifi_config ;;
 	status) ubus_wifi_cmd "status" "$2";;
@@ -296,6 +296,6 @@ case "$1" in
 	unload) wifi_unload "$2";;
 	recover) wifi_recover "$2";;
 	--help|help) usage;;
-	''|up) ubus call network reload; wifi_updown "enable" "$2";;
+	''|up) ubus call network reload; wifi_updown "enable" "$2" "$3";;
 	*) usage; exit 1;;
 esac
