base-files/wifi: Enable provision to unload/load wifi modules
Enable provision for unloading and loading of wifi modules,
this is required when we want to test wifi with module
parameters configured via UCI

Change-Id: Id0409a5e0f7bab56dcdd10dd46e2bddd4c20170a
Signed-off-by: Padma Raghunathan <padmar@codeaurora.org>

diff --git a/package/base-files/files/sbin/wifi b/package/base-files/files/sbin/wifi
--- a/package/base-files/files/sbin/wifi
+++ b/package/base-files/files/sbin/wifi
@@ -168,6 +168,23 @@ wifi_detect() {
 	); done
 }
 
+wifi_load() {
+	for driver in ${2:-$DRIVERS}; do (
+		if eval "type unload_$driver" 2>/dev/null >/dev/null; then
+			eval "unload_$driver" || echo "$driver: unload failed" >&2
+		else
+			echo "$driver: wifi unload not supported" >&2
+		fi
+	); done
+	for driver in ${2:-$DRIVERS}; do (
+		if eval "type load_$driver" 2>/dev/null >/dev/null; then
+			eval "load_$driver" || echo "$driver: load failed" >&2
+		else
+			echo "$driver: wifi load not supported" >&2
+		fi
+	); done
+}
+
 start_net() {(
 	local iface="$1"
 	local config="$2"
