ipq: hotplug: Modified script to show correct messages
Modified dump collection script to show proper messages.

Change-Id: I47854a69bae9600359ec38bc01d286a1bef19939
Signed-off-by: Amandeep Singh <amansing@codeaurora.org>

diff --git a/target/linux/ipq/base-files/etc/hotplug.d/dump/00-q6dump b/target/linux/ipq/base-files/etc/hotplug.d/dump/00-q6dump
--- a/target/linux/ipq/base-files/etc/hotplug.d/dump/00-q6dump
+++ b/target/linux/ipq/base-files/etc/hotplug.d/dump/00-q6dump
@@ -18,15 +18,21 @@
 SERVER=$(fw_printenv serverip | cut -c10-24);
 
 if [ ! -n "$SERVER" ]; then
-	echo "Wrong configuaration\nSERVER = $SERVER\n" > /dev/console
+	printf "%s\n" "Wrong configuaration SERVER = $SERVER" > /dev/console
 	exit 0
 fi
 
 if [ -e /dev/$DEVICENAME ] && [ "$ACTION" = add ]; then
-	echo "Collecting $DEVICENAME dump" > /dev/console
+	printf "%s\n" "Collecting $DEVICENAME dump in $SERVER" > /dev/console
 	cd /dev
-	tftp -l $DEVICENAME -p $SERVER
+	$(tftp -l $DEVICENAME -p $SERVER 2>&1)
+	if [ $? -eq 0 ]; then
+		printf "%s\n" "$DEVICENAME dump collected in $SERVER" \
+								> /dev/console
+	else
+		printf "%s\n" "$DEVICENAME dump collection failed in $SERVER" \
+								> /dev/console
+	fi
 	cd -
-	echo "$DEVICENAME dump collected in $SERVER" > /dev/console
 fi
 
